/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Todo {
  completed: Generated<number | null>;
  created_at: Generated<number | null>;
  id: number | null;
  title: string;
  updated_at: Generated<number | null>;
}

export interface DB {
  todo: Todo;
}
